#pragma once

#include <Engine/Utils/EnumClass.hpp>

enum class SHADER_TYPE {
    VERTEX_SHADER   = 1,
    HULL_SHADER     = VERTEX_SHADER << 1,
    DOMAIN_SHADER   = HULL_SHADER   << 1,
    GEOMETRY_SHADER = DOMAIN_SHADER << 1,
    FRAGMENT_SHADER = GEOMETRY_SHADER << 1
};

DECLARE_BITMASK(SHADER_TYPE)
