name: Välfärden
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-Debug-x64:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build Debug x64
      run: msbuild GameProject.vcxproj -p:Configuration=Debug -p:Platform=x64
  Build-Release-x64:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build Release x64
      run: msbuild GameProject.vcxproj -p:Configuration=Release -p:Platform=x64

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Lint Report
        uses: deep5050/cppcheck-action@master
        with:
          exclude_check: vendor
          platform: win64
          output_file: ./cppcheck_report

      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Lint Report
        run: python3 ./.github/workflows/read-lint-report.py --report ./cppcheck_report
          --modified-files $HOME/files_modified.json --added-files $HOME/files_added.json
