name: Välfärden
on: pull_request

jobs:
  Build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build Debug
      run: msbuild GameProject.vcxproj -p:Configuration=Debug -p:Platform=x64 /warnaserror

    - name: Build Release
      run: msbuild GameProject.vcxproj -p:Configuration=Release -p:Platform=x64 /warnaserror

  Lint:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Generate Lint Report
        run: python .github/workflows/generate-lint-report.py -o cppcheck_report.txt -i vendor

      - name: Get file changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Lint Report
        run: python ./.github/workflows/read-lint-report.py --report ./cppcheck_report.txt
          --modified-files $HOME/files_modified.json --added-files $HOME/files_added.json
