name: Build-Lint
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-Debug-x64:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build Debug x64
      run: msbuild GameProject.vcxproj -p:Configuration=Debug -p:Platform=x64
  Build-Release-x64:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build Release x64
      run: msbuild GameProject.vcxproj -p:Configuration=Release -p:Platform=x64

  lint:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Report
        uses: deep5050/cppcheck-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable: warning,performance,portability,information,unusedFunction,missingInclude
          exclude_check: dependencies
          platform: win64
          output_file: ./cppcheck_report
      - name: Print Report
        run: cat ./cppcheck_report
