name: Benchmark
on:
  push:
      branches:
        - master

jobs:
  benchmark:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Execute Premake
        run: .\premake5.exe vs2019

      - name: Build Production
        run: msbuild GameProject.vcxproj -p:Configuration=Production -p:Platform=x64  /warnaserror

      - name: Compile Shaders
        run: python tools/compile-shaders.py

      - name: Benchmark
        run: python .github/workflows/benchmark.py --bin build/bin/Production-windows-x86_64-x64/GameProject/GameProject.exe --vk benchmark_results_vk.json --dx11 benchmark_results_dx11.json

      - name: Update Charts
        run: python .github/workflows/update-charts.py --vk benchmark_results_vk.json --dx11 benchmark_results_dx11.json
        env:
          PAT: ${{ secrets.DOCS_PAT }}
