name: Benchmark
on:
  push:
      branches:
        - Benchmark-Workflow

jobs:
  benchmark:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Release x64
        run: msbuild GameProject.vcxproj -p:Configuration=Release -p:Platform=x64

      - name: Compile Shaders
        run: python tools/compile-shaders.py

      - name: Benchmark
        run: python .github/workflows/benchmark.py --bin x64/Release/GameProject.exe --vk benchmark_results_vk.json --dx11 benchmark_results_dx11.json

      # Fetch the pages repo so that the charts data can be updated
      - uses: actions/checkout@v2
        with:
          repository: 'TheoBerlin/SoloGamePages'
          ref: 'master'
          token: ${{ secrets.DOCS_PAT }}
          path: docs
          clean: false

      - name: Update Charts
        run: cd docs |
          python .github/workflows/update-charts.py --data docs/_data --vk ../benchmark_results_vk.json --dx11 ../benchmark_results_dx11.json --pat ${{ secrets.DOCS_PAT }}
